/**
 * Eagles stack complements — rosters verified against ESPN team pages.
 * Criteria: high-volume passing QB, top pass + rush offense, bye ≠ PHI (W9), excludes PHI & DEN rosters.
 * PHI/DEN matchup weeks from 2025 schedule (proxy for 2026).
 */
window.EAGLES_STACK = {
  eaglesBye: 9,
  rosterAsOf: '2026-08-01',
  rosterSource: 'https://www.espn.com/nfl/players',
  excludedNote: 'Philadelphia (your core stack) and Denver (elite defense) rosters excluded.',
  teams: [
    {
      abbr: 'DET',
      name: 'Detroit Lions',
      bye: 8,
      passRank: 2,
      rushRank: 4,
      qb: { name: 'Jared Goff', note: 'High volume — top-5 attempts' },
      wr1: 'Amon-Ra St. Brown',
      vsPhiDen: ['W12 @PHI', 'W15 @DEN'],
      players: [
        { pos: 'QB', name: 'Jared Goff', adp: 108, proj: 268 },
        { pos: 'RB', name: 'Jahmyr Gibbs', adp: 1.5, proj: 341 },
        { pos: 'RB', name: 'Isiah Pacheco', adp: 82, proj: 192 },
        { pos: 'WR', name: 'Amon-Ra St. Brown', adp: 12, proj: 298 },
        { pos: 'WR', name: 'Jameson Williams', adp: 74, proj: 212 },
        { pos: 'TE', name: 'Sam LaPorta', adp: 96, proj: 192 },
      ],
    },
    {
      abbr: 'CIN',
      name: 'Cincinnati Bengals',
      bye: 10,
      passRank: 3,
      rushRank: 12,
      qb: { name: 'Joe Burrow', note: 'Elite pass volume — 650+ att pace' },
      wr1: "Ja'Marr Chase",
      vsPhiDen: ['W7 @DEN', 'W13 vs PHI'],
      players: [
        { pos: 'QB', name: 'Joe Burrow', adp: 52, proj: 312 },
        { pos: 'WR', name: "Ja'Marr Chase", adp: 3, proj: 338 },
        { pos: 'WR', name: 'Tee Higgins', adp: 18, proj: 278 },
        { pos: 'WR', name: 'Andrei Iosivas', adp: 328, proj: 138 },
        { pos: 'RB', name: 'Chase Brown', adp: 14.5, proj: 267 },
        { pos: 'TE', name: 'Mike Gesicki', adp: 245, proj: 118 },
      ],
    },
    {
      abbr: 'KC',
      name: 'Kansas City Chiefs',
      bye: 10,
      passRank: 5,
      rushRank: 18,
      qb: { name: 'Patrick Mahomes', note: 'Perennial high-volume passer' },
      wr1: 'Rashee Rice',
      vsPhiDen: ['W10 @DEN', 'W14 vs PHI'],
      players: [
        { pos: 'QB', name: 'Patrick Mahomes', adp: 88, proj: 285 },
        { pos: 'WR', name: 'Rashee Rice', adp: 28, proj: 296 },
        { pos: 'WR', name: 'Xavier Worthy', adp: 44, proj: 245 },
        { pos: 'WR', name: 'Tyquan Thornton', adp: 148, proj: 162 },
        { pos: 'RB', name: 'Kenneth Walker III', adp: 38, proj: 248 },
        { pos: 'TE', name: 'Travis Kelce', adp: 72, proj: 205 },
      ],
    },
    {
      abbr: 'BUF',
      name: 'Buffalo Bills',
      bye: 7,
      passRank: 4,
      rushRank: 8,
      qb: { name: 'Josh Allen', note: 'Top pass + rush volume QB' },
      wr1: 'DJ Moore',
      vsPhiDen: ['W6 @PHI', 'W18 vs DEN'],
      players: [
        { pos: 'QB', name: 'Josh Allen', adp: 22, proj: 355 },
        { pos: 'RB', name: 'James Cook', adp: 26, proj: 272 },
        { pos: 'WR', name: 'DJ Moore', adp: 48, proj: 245 },
        { pos: 'WR', name: 'Khalil Shakir', adp: 82, proj: 228 },
        { pos: 'WR', name: 'Joshua Palmer', adp: 135, proj: 168 },
        { pos: 'WR', name: 'Keon Coleman', adp: 118, proj: 178 },
        { pos: 'TE', name: 'Dalton Kincaid', adp: 135, proj: 168 },
      ],
    },
    {
      abbr: 'BAL',
      name: 'Baltimore Ravens',
      bye: 7,
      passRank: 8,
      rushRank: 1,
      qb: { name: 'Lamar Jackson', note: 'Efficient + rush yards — top offense' },
      wr1: 'Zay Flowers',
      vsPhiDen: ['W5 @PHI', 'W16 vs DEN'],
      players: [
        { pos: 'QB', name: 'Lamar Jackson', adp: 38, proj: 328 },
        { pos: 'RB', name: 'Derrick Henry', adp: 16, proj: 285 },
        { pos: 'WR', name: 'Zay Flowers', adp: 34.5, proj: 259 },
        { pos: 'WR', name: 'Rashod Bateman', adp: 148, proj: 165 },
        { pos: 'TE', name: 'Mark Andrews', adp: 98, proj: 188 },
      ],
    },
    {
      abbr: 'LAR',
      name: 'Los Angeles Rams',
      bye: 8,
      passRank: 6,
      rushRank: 14,
      qb: { name: 'Matthew Stafford', note: 'Veteran volume passer' },
      wr1: 'Puka Nacua',
      vsPhiDen: ['W8 vs PHI', 'W11 @DEN'],
      players: [
        { pos: 'QB', name: 'Matthew Stafford', adp: 142, proj: 248 },
        { pos: 'WR', name: 'Puka Nacua', adp: 4, proj: 326 },
        { pos: 'WR', name: 'Davante Adams', adp: 51.5, proj: 240 },
        { pos: 'RB', name: 'Kyren Williams', adp: 24, proj: 265 },
        { pos: 'TE', name: 'Colby Parkinson', adp: 218, proj: 142 },
      ],
    },
    {
      abbr: 'HOU',
      name: 'Houston Texans',
      bye: 6,
      passRank: 9,
      rushRank: 16,
      qb: { name: 'C.J. Stroud', note: 'Young high-volume passer' },
      wr1: 'Nico Collins',
      vsPhiDen: ['W9 @DEN', 'W15 vs PHI'],
      players: [
        { pos: 'QB', name: 'C.J. Stroud', adp: 64, proj: 272 },
        { pos: 'WR', name: 'Nico Collins', adp: 14, proj: 305 },
        { pos: 'WR', name: 'Tank Dell', adp: 209.5, proj: 175 },
        { pos: 'WR', name: 'Xavier Hutchinson', adp: 273, proj: 152 },
        { pos: 'RB', name: 'David Montgomery', adp: 68, proj: 198 },
        { pos: 'RB', name: 'Woody Marks', adp: 88, proj: 185 },
        { pos: 'TE', name: 'Dalton Schultz', adp: 195, proj: 138 },
      ],
    },
    {
      abbr: 'ATL',
      name: 'Atlanta Falcons',
      bye: 5,
      passRank: 11,
      rushRank: 6,
      qb: { name: 'Michael Penix Jr.', note: 'Penix + Tua Tagovailoa compete post-ACL' },
      wr1: 'Drake London',
      vsPhiDen: ['W4 vs PHI', 'W13 @DEN'],
      players: [
        { pos: 'QB', name: 'Michael Penix Jr.', adp: 125, proj: 242 },
        { pos: 'QB', name: 'Tua Tagovailoa', adp: 999, proj: 165 },
        { pos: 'RB', name: 'Bijan Robinson', adp: 1.5, proj: 347 },
        { pos: 'WR', name: 'Drake London', adp: 32, proj: 268 },
        { pos: 'TE', name: 'Kyle Pitts', adp: 155, proj: 155 },
      ],
    },
    {
      abbr: 'MIN',
      name: 'Minnesota Vikings',
      bye: 6,
      passRank: 10,
      rushRank: 15,
      qb: { name: 'J.J. McCarthy', note: 'High-volume system QB' },
      wr1: 'Justin Jefferson',
      vsPhiDen: ['W3 @PHI', 'W12 vs DEN'],
      players: [
        { pos: 'QB', name: 'J.J. McCarthy', adp: 115, proj: 255 },
        { pos: 'WR', name: 'Justin Jefferson', adp: 6, proj: 318 },
        { pos: 'WR', name: 'Jordan Addison', adp: 99.5, proj: 250 },
        { pos: 'WR', name: 'Jauan Jennings', adp: 152, proj: 198 },
        { pos: 'RB', name: 'Aaron Jones', adp: 122, proj: 200 },
        { pos: 'RB', name: 'Jordan Mason', adp: 121.5, proj: 204 },
        { pos: 'TE', name: 'T.J. Hockenson', adp: 166.5, proj: 165 },
      ],
    },
    {
      abbr: 'DAL',
      name: 'Dallas Cowboys',
      bye: 10,
      passRank: 12,
      rushRank: 10,
      qb: { name: 'Dak Prescott', note: 'Consistent pass volume' },
      wr1: 'CeeDee Lamb',
      vsPhiDen: ['W11 @PHI', 'W8 vs DEN'],
      players: [
        { pos: 'QB', name: 'Dak Prescott', adp: 78, proj: 265 },
        { pos: 'WR', name: 'CeeDee Lamb', adp: 10, proj: 305 },
        { pos: 'WR', name: 'George Pickens', adp: 23.5, proj: 268 },
        { pos: 'RB', name: 'Javonte Williams', adp: 92, proj: 198 },
        { pos: 'TE', name: 'Jake Ferguson', adp: 128, proj: 162 },
      ],
    },
    {
      abbr: 'SF',
      name: 'San Francisco 49ers',
      bye: 14,
      passRank: 14,
      rushRank: 3,
      qb: { name: 'Brock Purdy', note: 'Efficient high-scoring offense' },
      wr1: 'Mike Evans',
      vsPhiDen: ['W16 @PHI', 'W6 vs DEN'],
      players: [
        { pos: 'QB', name: 'Brock Purdy', adp: 105, proj: 252 },
        { pos: 'RB', name: 'Christian McCaffrey', adp: 5, proj: 325 },
        { pos: 'WR', name: 'Mike Evans', adp: 38, proj: 255 },
        { pos: 'WR', name: 'Deebo Samuel', adp: 72, proj: 218 },
        { pos: 'WR', name: 'Christian Kirk', adp: 217, proj: 165 },
        { pos: 'TE', name: 'George Kittle', adp: 42, proj: 228 },
      ],
    },
    {
      abbr: 'GB',
      name: 'Green Bay Packers',
      bye: 5,
      passRank: 13,
      rushRank: 11,
      qb: { name: 'Jordan Love', note: 'Top-10 pass attempt pace' },
      wr1: 'Christian Watson',
      vsPhiDen: ['W10 @PHI', 'W9 vs DEN'],
      players: [
        { pos: 'QB', name: 'Jordan Love', adp: 98, proj: 258 },
        { pos: 'RB', name: 'Josh Jacobs', adp: 18, proj: 278 },
        { pos: 'WR', name: 'Christian Watson', adp: 68, proj: 228 },
        { pos: 'WR', name: 'Jayden Reed', adp: 72, proj: 235 },
        { pos: 'WR', name: 'Matthew Golden', adp: 95, proj: 205 },
        { pos: 'TE', name: 'Tucker Kraft', adp: 84.5, proj: 198 },
      ],
    },
    {
      abbr: 'LAC',
      name: 'Los Angeles Chargers',
      bye: 12,
      passRank: 15,
      rushRank: 9,
      qb: { name: 'Justin Herbert', note: 'High-volume arm talent' },
      wr1: 'Ladd McConkey',
      vsPhiDen: ['W15 @PHI', 'W17 @DEN'],
      players: [
        { pos: 'QB', name: 'Justin Herbert', adp: 72, proj: 268 },
        { pos: 'WR', name: 'Ladd McConkey', adp: 36, proj: 262 },
        { pos: 'WR', name: 'Quentin Johnston', adp: 89, proj: 227 },
        { pos: 'RB', name: 'Omarion Hampton', adp: 28, proj: 255 },
        { pos: 'TE', name: 'David Njoku', adp: 206.5, proj: 148 },
      ],
    },
    {
      abbr: 'IND',
      name: 'Indianapolis Colts',
      bye: 11,
      passRank: 16,
      rushRank: 7,
      qb: { name: 'Anthony Richardson', note: 'Dual-threat with rushing upside' },
      wr1: 'Alec Pierce',
      vsPhiDen: ['W12 vs PHI', 'W7 @DEN'],
      players: [
        { pos: 'QB', name: 'Anthony Richardson', adp: 385, proj: 172 },
        { pos: 'RB', name: 'Jonathan Taylor', adp: 8.5, proj: 302 },
        { pos: 'WR', name: 'Alec Pierce', adp: 78, proj: 232 },
        { pos: 'WR', name: 'Josh Downs', adp: 102, proj: 243 },
        { pos: 'TE', name: 'Tyler Warren', adp: 145, proj: 158 },
      ],
    },
    {
      abbr: 'SEA',
      name: 'Seattle Seahawks',
      bye: 8,
      passRank: 18,
      rushRank: 13,
      qb: { name: 'Sam Darnold', note: 'Volume-friendly system' },
      wr1: 'Jaxon Smith-Njigba',
      vsPhiDen: ['W17 @PHI', 'W4 vs DEN'],
      players: [
        { pos: 'QB', name: 'Sam Darnold', adp: 165, proj: 228 },
        { pos: 'WR', name: 'Jaxon Smith-Njigba', adp: 22, proj: 285 },
        { pos: 'RB', name: 'Jadarian Price', adp: 92, proj: 215 },
        { pos: 'RB', name: 'Zach Charbonnet', adp: 148, proj: 178 },
        { pos: 'WR', name: 'Cooper Kupp', adp: 95, proj: 195 },
        { pos: 'WR', name: 'Rashid Shaheed', adp: 128, proj: 172 },
      ],
    },
  ],
};
