/** Contract-year players — ADP: FantasyPros PPR consensus (Aug 2026). Proj: Draft Sharks consensus PPR where available. */
window.CONTRACT_YEAR_PLAYERS = {
  qb: [
    { id: 'qb-baker', name: 'Baker Mayfield', team: 'TB', adp: 115.0, proj: 248, note: 'Final year of deal' },
    { id: 'qb-fields', name: 'Justin Fields', team: 'KC', adp: 322.5, proj: 198, note: '1-year deal' },
    { id: 'qb-cousins', name: 'Kirk Cousins', team: 'LV', adp: 237.5, proj: 185, note: 'Final year' },
    { id: 'qb-richardson', name: 'Anthony Richardson', team: 'IND', adp: 385.0, proj: 172, note: 'Final rookie year' },
    { id: 'qb-genosmith', name: 'Geno Smith', team: 'NYJ', adp: 999, proj: 165, note: '1-year deal' },
    { id: 'qb-flacco', name: 'Joe Flacco', team: 'CIN', adp: 999, proj: 158, note: '1-year deal' },
  ],
  rb: [
    { id: 'rb-gibbs', name: 'Jahmyr Gibbs', team: 'DET', adp: 1.5, proj: 341, note: '5th-yr option; extension eligible' },
    { id: 'rb-bijan', name: 'Bijan Robinson', team: 'ATL', adp: 1.5, proj: 347, note: '5th-yr option; extension eligible' },
    { id: 'rb-taylor', name: 'Jonathan Taylor', team: 'IND', adp: 8.5, proj: 302, note: 'Final year of extension' },
    { id: 'rb-chaseb', name: 'Chase Brown', team: 'CIN', adp: 14.5, proj: 267, note: 'Final rookie year' },
    { id: 'rb-swift', name: "D'Andre Swift", team: 'CHI', adp: 51.5, proj: 221, note: 'Final year of deal' },
    { id: 'rb-pollard', name: 'Tony Pollard', team: 'TEN', adp: 78.5, proj: 214, note: 'Final year of deal' },
    { id: 'rb-mason', name: 'Jordan Mason', team: 'MIN', adp: 121.5, proj: 204, note: 'Final year of deal' },
    { id: 'rb-jones', name: 'Aaron Jones', team: 'MIN', adp: 122.0, proj: 200, note: '1-year deal' },
    { id: 'rb-spears', name: 'Tyjae Spears', team: 'TEN', adp: 157.0, proj: 186, note: 'Final rookie year' },
    { id: 'rb-charb', name: 'Zach Charbonnet', team: 'SEA', adp: 166.5, proj: 182, note: 'Final rookie year' },
    { id: 'rb-kamara', name: 'Alvin Kamara', team: 'NO', adp: 175.5, proj: 229, note: 'Final year of deal' },
    { id: 'rb-bigsby', name: 'Tank Bigsby', team: 'PHI', adp: 174.0, proj: 145, note: 'Final rookie year' },
    { id: 'rb-brobin', name: 'Brian Robinson', team: 'ATL', adp: 172.0, proj: 142, note: '1-year deal' },
    { id: 'rb-tucker', name: 'Sean Tucker', team: 'TB', adp: 179.5, proj: 138, note: '1-year deal' },
    { id: 'rb-hill', name: 'Justice Hill', team: 'BAL', adp: 249.5, proj: 128, note: 'Final year of deal' },
    { id: 'rb-miller', name: 'Kendre Miller', team: 'NO', adp: 261.0, proj: 118, note: 'Final rookie year' },
    { id: 'rb-roschon', name: 'Roschon Johnson', team: 'CHI', adp: 999, proj: 95, note: 'Final rookie year' },
    { id: 'rb-gray', name: 'Eric Gray', team: 'NYG', adp: 999, proj: 72, note: 'Final rookie year' },
  ],
  wr: [
    { id: 'wr-puka', name: 'Puka Nacua', team: 'LAR', adp: 4.0, proj: 326, note: 'Final rookie year' },
    { id: 'wr-pickens', name: 'George Pickens', team: 'DAL', adp: 23.5, proj: 268, note: 'Franchise tag' },
    { id: 'wr-rice', name: 'Rashee Rice', team: 'KC', adp: 28.0, proj: 296, note: 'Final rookie year' },
    { id: 'wr-flowers', name: 'Zay Flowers', team: 'BAL', adp: 34.5, proj: 259, note: '5th-yr option' },
    { id: 'wr-adams', name: 'Davante Adams', team: 'LAR', adp: 51.5, proj: 240, note: 'Final year of deal' },
    { id: 'wr-jwash', name: 'Parker Washington', team: 'JAX', adp: 69.0, proj: 228, note: 'Final rookie year' },
    { id: 'wr-johnston', name: 'Quentin Johnston', team: 'LAC', adp: 89.0, proj: 227, note: '5th-yr option' },
    { id: 'wr-mwilson', name: 'Michael Wilson', team: 'ARI', adp: 92.0, proj: 225, note: 'Final rookie year' },
    { id: 'wr-addison', name: 'Jordan Addison', team: 'MIN', adp: 99.5, proj: 250, note: '5th-yr option' },
    { id: 'wr-downs', name: 'Josh Downs', team: 'IND', adp: 102.0, proj: 243, note: 'Final rookie year' },
    { id: 'wr-jennings', name: 'Jauan Jennings', team: 'MIN', adp: 152.0, proj: 198, note: '1-year deal' },
    { id: 'wr-tucker', name: 'Tre Tucker', team: 'LV', adp: 156.0, proj: 195, note: 'Final rookie year' },
    { id: 'wr-mooney', name: 'Darnell Mooney', team: 'NYG', adp: 205.0, proj: 172, note: '1-year deal' },
    { id: 'wr-boutte', name: 'Kayshon Boutte', team: 'NE', adp: 216.0, proj: 168, note: 'Final rookie year' },
    { id: 'wr-kirk', name: 'Christian Kirk', team: 'SF', adp: 217.0, proj: 165, note: '1-year deal' },
    { id: 'wr-wicks', name: 'Dontayvion Wicks', team: 'PHI', adp: 246.5, proj: 158, note: '1-year prove-it' },
    { id: 'wr-hutch', name: 'Xavier Hutchinson', team: 'HOU', adp: 273.0, proj: 152, note: 'Final rookie year' },
    { id: 'wr-tillman', name: 'Cedric Tillman', team: 'CLE', adp: 279.0, proj: 148, note: 'Final rookie year' },
    { id: 'wr-dell', name: 'Tank Dell', team: 'HOU', adp: 209.5, proj: 175, note: 'Final rookie year' },
    { id: 'wr-brown', name: 'Marquise Brown', team: 'PHI', adp: 318.0, proj: 142, note: '1-year deal' },
    { id: 'wr-iosivas', name: 'Andrei Iosivas', team: 'CIN', adp: 328.5, proj: 138, note: 'Final rookie year' },
    { id: 'wr-douglas', name: 'DeMario Douglas', team: 'NE', adp: 327.0, proj: 136, note: 'Final rookie year' },
    { id: 'wr-mims', name: 'Marvin Mims', team: 'DEN', adp: 339.0, proj: 134, note: 'Final rookie year' },
    { id: 'wr-hollins', name: 'Mack Hollins', team: 'NE', adp: 375.0, proj: 118, note: 'Final year' },
    { id: 'wr-dulin', name: 'Ashton Dulin', team: 'IND', adp: 264.0, proj: 112, note: 'Final year' },
    { id: 'wr-drobin', name: 'Demarcus Robinson', team: 'SF', adp: 999, proj: 108, note: 'Final year' },
  ],
  te: [
    { id: 'te-kraft', name: 'Tucker Kraft', team: 'GB', adp: 84.5, proj: 198, note: 'Final rookie year' },
    { id: 'te-laporta', name: 'Sam LaPorta', team: 'DET', adp: 96.0, proj: 192, note: 'Final rookie year' },
    { id: 'te-goedert', name: 'Dallas Goedert', team: 'PHI', adp: 129.5, proj: 178, note: 'Final year' },
    { id: 'te-hock', name: 'T.J. Hockenson', team: 'MIN', adp: 166.5, proj: 165, note: 'Final year' },
    { id: 'te-henry', name: 'Hunter Henry', team: 'NE', adp: 157.0, proj: 162, note: '1-year deal' },
    { id: 'te-njoku', name: 'David Njoku', team: 'LAC', adp: 206.5, proj: 148, note: '1-year deal' },
    { id: 'te-parkinson', name: 'Colby Parkinson', team: 'LAR', adp: 218.0, proj: 142, note: '1-year deal' },
    { id: 'te-engram', name: 'Evan Engram', team: 'DEN', adp: 282.5, proj: 128, note: 'Final year' },
    { id: 'te-higgins', name: 'Elijah Higgins', team: 'ARI', adp: 999, proj: 95, note: 'Final rookie year' },
  ],
};
